name: Update Language Chart

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests matplotlib

    - name: Run script to generate chart
      run: python scripts/generate_language_chart.py

    - name: Commit and push updated chart
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add most_used_languages.png
        git commit -m 'Update language chart'
        git push
